"use strict";

const STATES = Object.freeze({
  CAPTURED: "CAPTURED",
  INVALID: "INVALID",
  DUPLICATE: "DUPLICATE",
  TF_MISSING: "TF_MISSING",
  TF_MISMATCH: "TF_MISMATCH",
  TF_VERIFY_FAILED: "TF_VERIFY_FAILED",
  TF_RETAINED: "TF_RETAINED",
  READY_FOR_ROUTING: "READY_FOR_ROUTING",
  BUYER_ACCEPTED: "BUYER_ACCEPTED",
  BUYER_REJECTED: "BUYER_REJECTED",
  GHL_DELIVERED: "GHL_DELIVERED",
  QUARANTINE: "QUARANTINE"
});

module.exports = { STATES };
